version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      non-major:
        update-types: ["minor", "patch"]
      major:
        update-types: ["major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
    groups:
      actions-non-major:
        update-types: ["minor", "patch"]
